### ISSUE TITLE
Endermage Kit

### ISSUE THREAD

**Issue by Nickahh** [Tr3xDragon/ReactPvP#18]
Kit Name: Endermage

Sword: Iron

    Enchants: Sharpness 1

Helm: Leather - Purple

    Enchants: Prot 1

Chest: Leather - Purple

    Enchants: Prot 2

Legs: Iron 

    Enchants: None

Boots: Leather / Purple

    Enchants: Prot 1

Icon: Portal block

Inv of soup(Y/N): Y
Abilities: Can right click with the portal to bring everyone above and below them in a radius to where they're standing.  Maybe a 3x3 radius with the player in the middle.

**Comment by SackBoi** [comment]
+1
