### ISSUE TITLE
Grappler Kit

### ISSUE THREAD

**Issue by Nickahh** [Tr3xDragon/ReactPvP#19]
Kit Name: Grappler

Sword: Iron

    Enchants: Sharpness 1

Helm: Iron

    Enchants: None.

Chest: Leather - red

    Enchants: Prot 2

Legs: Leather - red

    Enchants: Prot 2

Boots: Iron 

    Enchants: None

Icon: Lead

Inv of soup(Y/N): Y
Abilities: Can use a fishing rod to PULL them self to whatever the hook lands on.

**Comment by SackBoi** [comment]
+1
