### ISSUE TITLE
Builder

### ISSUE THREAD

**Issue by Nickahh** [Tr3xDragon/ReactPvP#23]
Kit Name: Builder

Sword: Iron

Enchants: None

Helm: Diamond

Enchants: None.

Chest: Leather - Black

Enchants: Prot 1

Legs: Leather - Black

Enchants: Prot 1

Boots: Gold

Enchants: Unbreaking 3, Feather fall ?Maybe?

Icon: Crafting table

Inv of soup(Y/N): Y
Abilities: Has 6 Blocks( Probably cobblestone to blend in OR Gold blocks to stand out ) that they can place anywhere in the world that last for 5 seconds then reappear in the players inventory.

**Comment by SackBoi** [comment]
I'm a bit curious about this one, I'm at +0 for now.

**Comment by Tr3xDragon** [comment]
+0 for now
